version: 0.2

env:
  variables:
    DOTNET_VERSION: "10.0.101"

phases:
  install:
    commands:
      - echo Installing .NET $DOTNET_VERSION
      - export HOME=/root
      - curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --version $DOTNET_VERSION --install-dir /root/.dotnet
      - export PATH="$PATH:/root/.dotnet"
      - dotnet --version

  pre_build:
    commands:
      - dotnet restore

  build:
    commands:
      - dotnet publish -c Release -o publish

artifacts:
  files:
    - '**/*'
  base-directory: publish
