version: 0.2

phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh -o dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --version 10.0.101
      - export PATH="$HOME/.dotnet:$PATH"
      - dotnet --version

  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release -o publish

artifacts:
  files:
    - '**/*'
  base-directory: publish
